apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIyODQyNzU3MDUxMzAuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHt9LAoJCSJwdWJsaWMuZWNyLmF3cyI6IHt9LAoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiV2x5YjI1emRqcG5hSEJmVWxWaWRuWTVRMnRzWmpKamVWaHRSRk00TW1wTVExaExSRTQ0WkROc00wWk9ia1p4IgoJCX0KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwKCSJwbHVnaW5zIjogewoJCSJkZWJ1ZyI6IHsKCQkJImhvb2tzIjogImV4ZWMiCgkJfSwKCQkic2NvdXQiOiB7CgkJCSJob29rcyI6ICJwdWxsLGJ1aWxkeCBidWlsZCIKCQl9Cgl9LAoJImZlYXR1cmVzIjogewoJCSJob29rcyI6ICJ0cnVlIgoJfQp9Cg==
type: kubernetes.io/dockerconfigjson
